#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Allow mpirun as root (Docker)
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

# Continuation stage: no initial->0 copy, no blockMesh, no setFields, no
# decomposePar. This case must be seeded first by copying the previous
# stage's final time directory (processor*/ dirs if parallel) into here;
# startFrom latestTime in system/controlDict then resumes from it.

NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/decomposeParDict)

if [ "$NPROCS" -gt 1 ]; then
    runParallel laserbeamFoam
else
    runApplication laserbeamFoam
fi
